/home/lhp/anaconda3/envs/tf13/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lhp/anaconda3/envs/tf13/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lhp/anaconda3/envs/tf13/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lhp/anaconda3/envs/tf13/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/lhp/anaconda3/envs/tf13/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/lhp/anaconda3/envs/tf13/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "put_all_together.py", line 116, in <module>
    main()
  File "put_all_together.py", line 112, in main
    AllTogether(already_have_data=False, process_drug_n=5000, pubmed_search_ret_max=20, num_epochs=200).run_all_together()
  File "put_all_together.py", line 61, in run_all_together
    drug_abstract_all = SearchMultipleTerms(search_terms, retmax=self.pubmed_search_ret_max).search_pubmed()
  File "/home/lhp/Documents/drugRepo/drug_reposition/drugRepoSource/search_pubmed_with_terms.py", line 16, in search_pubmed
    article_pd = PubMedBiopython(search_term, retmax=self.retmax).search_pubmed()
  File "/home/lhp/Documents/drugRepo/drug_reposition/drugRepoSource/pubmed_search.py", line 43, in search_pubmed
    handle = Entrez.efetch(db='pubmed', id=id_string, retmode='xml')
  File "/home/lhp/anaconda3/envs/tf13/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 195, in efetch
    return _open(cgi, variables, post=post)
  File "/home/lhp/anaconda3/envs/tf13/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 555, in _open
    handle = _urlopen(cgi)
  File "/home/lhp/anaconda3/envs/tf13/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/lhp/anaconda3/envs/tf13/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/lhp/anaconda3/envs/tf13/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/lhp/anaconda3/envs/tf13/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/lhp/anaconda3/envs/tf13/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/lhp/anaconda3/envs/tf13/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
